### ISSUE TITLE
JavaScript error on File menu Export Report...

### ISSUE THREAD

**Issue by DaveGunn** [daisy/ace-gui#26]
On Win10, File> Export Report results in and error
JavaScript error occurred in the main process
Uncaught Exception: 
TypeError: path must be a string or Buffer
 at Object.fs.open (fsjs:636:11)
 at Object.module.(anonymous function) [as open] (ELECTRON_ASARjs:200:20)
 at WriteStream.open (fsjs:2158:6)
 at new WriteStream (fsjs:2144:10)
 at Object.fs.createWriteStream (fsjs:210610)
 at Readable.<anonymous> (local path)\background.js:1:11287)
 at emitNone (events.js:106:13)
 at Readable.emit (events.js:208:7)
 at endReadableNT (_stream_readable.js:1056:12)
 at _combinedTickCallback (internal/process/next_tick.js:138:11)

**Comment by marisademeglio** [comment]
I am able to reproduce this
